import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';

@Component({
  // ... existing metadata ...
  imports: [CommonModule, ReactiveFormsModule],
  // ... existing metadata ...
})
// ... existing code ... 